spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia-tesla-k80  # or your GPU type
      containers:
        - name: app
          image: ghcr.io/your-org/hyperion:latest
          resources:
            requests:
              nvidia.com/gpu: 1
              cpu: "1"
              memory: "4Gi"
            limits:
              nvidia.com/gpu: 1
              cpu: "2"
              memory: "8Gi"