apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mms-app-hpa
  namespace: mms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mms-app
  minReplicas: 2
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
