apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyperion.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperion.labels" . | nindent 4 }}
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hyperion.selectorLabels" . | nindent 6 }}
      component: redis
  template:
    metadata:
      labels:
        {{- include "hyperion.selectorLabels" . | nindent 8 }}
        component: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default "7-alpine" }}
        imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
