apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperion.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperion.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    {{- include "hyperion.selectorLabels" . | nindent 4 }}
    component: redis
