apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperion.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port | default 8000 }}
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    {{- include "hyperion.selectorLabels" . | nindent 4 }}
