filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

  # Include container metadata
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  # Only collect logs from our services
  - drop_event:
      when:
        not:
          or:
            - contains:
                container.name: "hyperion-app"
            - contains:
                container.name: "hyperion-redis"
            - contains:
                container.name: "hyperion-prometheus"
            - contains:
                container.name: "hyperion-grafana"
            - contains:
                container.name: "hyperion-jaeger"

  # Add custom fields
  - add_fields:
      target: hyperion
      fields:
        platform: "ml-inference"
        phase: "3"

  # Decode JSON logs from FastAPI
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true

# Configure multiline patterns for stack traces
filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 10

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3
  escape_html: false

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Processors
processors:
- add_host_metadata:
    when.not.contains.tags: forwarded

# Template settings
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression